### ISSUE TITLE
TypeError: obj.nodes is not iterable at convert

### ISSUE THREAD

**Issue by jywarren** [publiclab/image-sequencer-app#37]
I got this error, and I think i'm submitting a request where this is a string and not JSON?

```js
TypeError: obj.nodes is not iterable at convert (/app/src/api/v2/util/converter-multiSequencer.js:13:29) at redirectToProcess (/app/src/api/v2/index.js:32:181) at app.use (/app/src/api/v2/index.js:27:7) at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5) at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13) at /app/node_modules/express/lib/router/index.js:284:7 at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12) at next (/app/node_modules/express/lib/router/index.js:275:10) at Function.handle (/app/node_modules/express/lib/router/index.js:174:3) at router (/app/node_modules/express/lib/router/index.js:47:12)

```

**Comment by jywarren** [comment]
I'm working from code in https://github.com/publiclab/Leaflet.DistortableImage/pull/485 and i realized, we are sending a string, not JSON -- because https://github.com/publiclab/mapknitter-exporter-sinatra#usage actually wants a string! Here, we want JSON, not stringified. So we're all good but perhaps in the future we may need to catch this and convert stringified JSON to JSON.
